version: "3.9"

services:
  app:
    build: .
    container_name: url_app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/url_db

  db:
    image: postgres:15
    container_name: url_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: url_db
    ports:
      - "5432:5432"
